# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: plytools/circleci-cloak-tee:v0.2.0
    working_directory: ~/cloak-tee
    steps:
      - checkout
      - run:
          name: Submodele update
          command: git submodule update --init --recursive
      - run:
          name: Make build directory
          command: mkdir build
      - run:
          name: CMake build
          command: cmake .. -DCMAKE_BUILD_TYPE=Debug -L
          working_directory: build
      - run:
          name: Build resources
          command: make
          working_directory: build
      - run:
          name: Test case
          command: ctest -VV
          working_directory: build
